### ISSUE TITLE
build not same as src

### ISSUE THREAD

**Issue by diegogarciar** [geospoc/v-mapbox-geocoder#141]
Hello, I was just able to test your branch, I see that you tried to require mapboxgl only if using markers, here's your code which looks good
```
 mapboxgl: {
      type: Object,
      default: null,
      required: this.marker,
    },

```
here's the output at `v-mapbox-geocoder.esm.js`
```
 mapboxgl: {
      type: Object,
      default: null,
      required: undefined.marker
    },
```
I seems you can't access `this` at this point or the compiler at least can't find it

**Comment by woshikie** [comment]
Downgraded to `0.2.3` as a workaround for now. [More instructions here](https://github.com/geospoc/v-mapbox-geocoder/packages/233812?version=0.2.3)
I can't seem to be able to install from this Github repo with
`npm install https://github.com/geospoc/v-mapbox-grocoder.git`
It would be a better workaround to get `v0.3.0` working.

<details>
<summary>Error output</summary>

```
> @geospoc/v-mapbox-geocoder@0.3.0 preinstall <omitted path>\node_modules\@geospoc\v-mapbox-geocoder
> npx npm-force-resolutions

npx: installed 5 in 2.516s
ENOENT: no such file or directory, open './package-lock.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @geospoc/v-mapbox-geocoder@0.3.0 preinstall: `npx npm-force-resolutions`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @geospoc/v-mapbox-geocoder@0.3.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <omitted path>\AppData\Roaming\npm-cache\_logs\2020-10-12T15_52_11_539Z-debug.log

```

</details>

<details>
<summary> debug.log </summary>

```
<omitted silly saveTrees>
152 verbose stack Error: @geospoc/v-mapbox-geocoder@0.3.0 preinstall: `npx npm-force-resolutions`
152 verbose stack Exit status 1
152 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
152 verbose stack     at EventEmitter.emit (events.js:315:20)
152 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
152 verbose stack     at ChildProcess.emit (events.js:315:20)
152 verbose stack     at maybeClose (internal/child_process.js:1021:16)
152 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
153 verbose pkgid @geospoc/v-mapbox-geocoder@0.3.0
154 verbose cwd D:\Work and stuff\Uni\FYP\BDAST-Frontend
155 verbose Windows_NT 10.0.19042
156 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "https://github.com/geospoc/v-mapbox-geocoder.git"
157 verbose node v12.18.4
158 verbose npm  v6.14.6
159 error code ELIFECYCLE
160 error errno 1
161 error @geospoc/v-mapbox-geocoder@0.3.0 preinstall: `npx npm-force-resolutions`
161 error Exit status 1
162 error Failed at the @geospoc/v-mapbox-geocoder@0.3.0 preinstall script.
162 error This is probably not a problem with npm. There is likely additional logging output above.
163 verbose exit [ 1, true ]
```

</details>

**Comment by vinayakkulkarni** [comment]
npx force-resolutions seems to be the culprit. will do a fix right away!

**Comment by karol-bujacek** [comment]
@vinayakkulkarni, did you fixed the issue already?

**Comment by vinayakkulkarni** [comment]
@karol-bujacek - Yep, was fixed in https://github.com/geospoc/v-mapbox-geocoder/pull/171/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L88-L90

**Comment by karol-bujacek** [comment]
@vinayakkulkarni, the error with ‘undefined.markers’ is still not fixed in the latest package – https://github.com/geospoc/v-mapbox-geocoder/packages/233812
