### ISSUE TITLE
Package does not exist upon installation

### ISSUE THREAD

**Issue by MAvalleza** [geospoc/v-mapbox-geocoder#83]
I tried installing this in my project but it seems that the `@geospoc/v-mapbox-geocoder` does not exist.

Here are my logs:
`0 info it worked if it ends with ok
1 verbose cli [ '/Users/ezamar/.nvm/versions/node/v10.16.3/bin/node',
1 verbose cli   '/Users/ezamar/.nvm/versions/node/v10.16.3/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@geospoc/v-mapbox-geocoder' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose npm-session 4e5e3411e3c17e41
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 http://128.199.210.61:4873/@geospoc%2fv-mapbox-geocoder 248ms
8 http fetch GET 404 http://128.199.210.61:4873/@geospoc%2fv-mapbox-geocoder 187ms
9 silly fetchPackageMetaData error for @geospoc/v-mapbox-geocoder@latest 404 Not Found - GET http://128.199.210.61:4873/@geospoc%2fv-mapbox-geocoder - no such package available
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 12246ms
12 verbose stack Error: 404 Not Found - GET http://128.199.210.61:4873/@geospoc%2fv-mapbox-geocoder - no such package available
12 verbose stack     at res.buffer.catch.then.body (/Users/ezamar/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
13 verbose statusCode 404
14 verbose pkgid @geospoc/v-mapbox-geocoder@latest
15 verbose cwd /Users/ezamar/Desktop/MYCURE/vue-cms
16 verbose Darwin 18.7.0
17 verbose argv "/Users/ezamar/.nvm/versions/node/v10.16.3/bin/node" "/Users/ezamar/.nvm/versions/node/v10.16.3/bin/npm" "i" "@geospoc/v-mapbox-geocoder"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code E404
21 error 404 Not Found - GET http://128.199.210.61:4873/@geospoc%2fv-mapbox-geocoder - no such package available
22 error 404
23 error 404 '@geospoc/v-mapbox-geocoder@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]
`

**Comment by vinayakkulkarni** [comment]
You need to be logged in to the GitHub Package registry to fetch the package.

try this:

```sh
$ npm login --registry=https://npm.pkg.github.com --scope=@geospoc
$ npm install
```

**Comment by razza12** [comment]
Hi,

Thanks for the maintaining the package, am finding it very useful.

Is there any chance of publishing to public package to simplify deployments etc?

Thanks in advance,

**Comment by vinayakkulkarni** [comment]
@razza12 thanks for the kind words!

This is a public package!
Instead of using `npm` as package registry, we are using `GitHub package registry`

if you add a `.npmrc` like this in your project root directory, your deployments will be simplified:

```
registry=https://registry.npmjs.org
@geospoc:registry=https://npm.pkg.github.com
```

**Comment by woshikie** [comment]
Hope the solution to this issue be posted in the readme. Took me some time before I found this issue.

**Comment by anthonylebrun** [comment]
Have to agree with @razza12, is there some practical reason not to host it on npm? Having developers generate a github Personal Access Token just to download a public package is highly irregular. It also excludes people who may not have or can't have a github account (e.g. embargo).

For those who are wondering who do have a github account and are still wondering what you need to do:

In your .npmrc:
```
//npm.pkg.github.com/:_authToken=[GENERATED GITHUB PERSONAL ACCESS TOKEN]
registry=https://registry.npmjs.org
@geospoc:registry=https://npm.pkg.github.com
```

Where `[GENERATED GITHUB PERSONAL ACCESS TOKEN]` is the token generated here:

https://github.com/settings/tokens/new

Required permissions:
- ` public_repo`
- `read:packages`

**Comment by ghost** [comment]
Getting permission denied, i am using a PAT with both of those permissions..
